//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4927
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Schemas {
    using System.Xml.Serialization;
    
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://proveedores.alsuper.com/CFD")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://proveedores.alsuper.com/CFD", IsNullable=false)]
    public partial class Alsuper {
        
        private AlsuperConcepto[] conceptosField;
        
        private string versionField;
        
        private string remisionField;
        
        private string ordenDeCompraField;
        
        private string sucursalField;
        
        private string citaField;
        
        private System.DateTime fechaCitaField;
        
        private bool fechaCitaFieldSpecified;
        
        private AlsuperTipoMoneda tipoMonedaField;
        
        private bool tipoMonedaFieldSpecified;
        
        private float tipoDeCambioField;
        
        private bool tipoDeCambioFieldSpecified;
        
        private AlsuperTipoBulto tipoBultoField;
        
        private bool tipoBultoFieldSpecified;
        
        private decimal valorFleteField;
        
        private bool valorFleteFieldSpecified;
        
        private string emailField;
        
        public Alsuper() {
            this.versionField = "1.0";
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Concepto", IsNullable=false)]
        public AlsuperConcepto[] Conceptos {
            get {
                return this.conceptosField;
            }
            set {
                this.conceptosField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remision {
            get {
                return this.remisionField;
            }
            set {
                this.remisionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string ordenDeCompra {
            get {
                return this.ordenDeCompraField;
            }
            set {
                this.ordenDeCompraField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string cita {
            get {
                return this.citaField;
            }
            set {
                this.citaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime fechaCita {
            get {
                return this.fechaCitaField;
            }
            set {
                this.fechaCitaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCitaSpecified {
            get {
                return this.fechaCitaFieldSpecified;
            }
            set {
                this.fechaCitaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AlsuperTipoMoneda tipoMoneda {
            get {
                return this.tipoMonedaField;
            }
            set {
                this.tipoMonedaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoMonedaSpecified {
            get {
                return this.tipoMonedaFieldSpecified;
            }
            set {
                this.tipoMonedaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float tipoDeCambio {
            get {
                return this.tipoDeCambioField;
            }
            set {
                this.tipoDeCambioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoDeCambioSpecified {
            get {
                return this.tipoDeCambioFieldSpecified;
            }
            set {
                this.tipoDeCambioFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AlsuperTipoBulto tipoBulto {
            get {
                return this.tipoBultoField;
            }
            set {
                this.tipoBultoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoBultoSpecified {
            get {
                return this.tipoBultoFieldSpecified;
            }
            set {
                this.tipoBultoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal valorFlete {
            get {
                return this.valorFleteField;
            }
            set {
                this.valorFleteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorFleteSpecified {
            get {
                return this.valorFleteFieldSpecified;
            }
            set {
                this.valorFleteFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://proveedores.alsuper.com/CFD")]
    public partial class AlsuperConcepto {
        
        private string noPartidaField;
        
        private string codigoDeBarrasField;
        
        private decimal factorEmpaqueField;
        
        private bool factorEmpaqueFieldSpecified;
        
        private decimal empaqueIngresoField;
        
        private bool empaqueIngresoFieldSpecified;
        
        private decimal costoPagarField;
        
        private bool costoPagarFieldSpecified;
        
        private decimal valorIvaField;
        
        private bool valorIvaFieldSpecified;
        
        private decimal valorIepsField;
        
        private bool valorIepsFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string noPartida {
            get {
                return this.noPartidaField;
            }
            set {
                this.noPartidaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codigoDeBarras {
            get {
                return this.codigoDeBarrasField;
            }
            set {
                this.codigoDeBarrasField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal factorEmpaque {
            get {
                return this.factorEmpaqueField;
            }
            set {
                this.factorEmpaqueField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool factorEmpaqueSpecified {
            get {
                return this.factorEmpaqueFieldSpecified;
            }
            set {
                this.factorEmpaqueFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal empaqueIngreso {
            get {
                return this.empaqueIngresoField;
            }
            set {
                this.empaqueIngresoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool empaqueIngresoSpecified {
            get {
                return this.empaqueIngresoFieldSpecified;
            }
            set {
                this.empaqueIngresoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal costoPagar {
            get {
                return this.costoPagarField;
            }
            set {
                this.costoPagarField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool costoPagarSpecified {
            get {
                return this.costoPagarFieldSpecified;
            }
            set {
                this.costoPagarFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal valorIva {
            get {
                return this.valorIvaField;
            }
            set {
                this.valorIvaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorIvaSpecified {
            get {
                return this.valorIvaFieldSpecified;
            }
            set {
                this.valorIvaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal valorIeps {
            get {
                return this.valorIepsField;
            }
            set {
                this.valorIepsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorIepsSpecified {
            get {
                return this.valorIepsFieldSpecified;
            }
            set {
                this.valorIepsFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://proveedores.alsuper.com/CFD")]
    public enum AlsuperTipoMoneda {
        
        /// <comentarios/>
        Pesos,
        
        /// <comentarios/>
        Dolares,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://proveedores.alsuper.com/CFD")]
    public enum AlsuperTipoBulto {
        
        /// <comentarios/>
        cajas,
        
        /// <comentarios/>
        bultos,
        
        /// <comentarios/>
        rejas,
    }
}
