//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace Schemas {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.amazon.com.mx/AmazonAddenda")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.amazon.com.mx/AmazonAddenda", IsNullable=false)]
    public partial class ElementosAmazon {
        
        private string textoLibreField;
        
        private ElementosAmazonLosAtributos[] losAtributosField;
        
        /// <remarks/>
        public string TextoLibre {
            get {
                return this.textoLibreField;
            }
            set {
                this.textoLibreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LosAtributos")]
        public ElementosAmazonLosAtributos[] LosAtributos {
            get {
                return this.losAtributosField;
            }
            set {
                this.losAtributosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.amazon.com.mx/AmazonAddenda")]
    public partial class ElementosAmazonLosAtributos {
        
        private string identificacionUnicaField;
        
        private string nombreDelAtributoField;
        
        private string valorDelAtributoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string identificacionUnica {
            get {
                return this.identificacionUnicaField;
            }
            set {
                this.identificacionUnicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nombreDelAtributo {
            get {
                return this.nombreDelAtributoField;
            }
            set {
                this.nombreDelAtributoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valorDelAtributo {
            get {
                return this.valorDelAtributoField;
            }
            set {
                this.valorDelAtributoField = value;
            }
        }
    }
}
