//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8794
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Schemas.ComercExt11modif {
    using System.Xml.Serialization;
    
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/ComercioExterior11")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sat.gob.mx/ComercioExterior11", IsNullable=false)]
    public partial class ComercioExterior {
        
        private ComercioExteriorEmisor emisorField;
        
        private ComercioExteriorPropietario[] propietarioField;
        
        private ComercioExteriorReceptor receptorField;
        
        private ComercioExteriorDestinatario[] destinatarioField;
        
        private ComercioExteriorMercancia[] mercanciasField;
        
        private string versionField;
        
        private c_MotivoTraslado motivoTrasladoField;
        
        private bool motivoTrasladoFieldSpecified;
        
        private c_TipoOperacion tipoOperacionField;
        
        private c_ClavePedimento claveDePedimentoField;
        
        private bool claveDePedimentoFieldSpecified;
        
        private int certificadoOrigenField;
        
        private bool certificadoOrigenFieldSpecified;
        
        private string numCertificadoOrigenField;
        
        private string numeroExportadorConfiableField;
        
        private c_INCOTERM incotermField;
        
        private bool incotermFieldSpecified;
        
        private int subdivisionField;
        
        private bool subdivisionFieldSpecified;
        
        private string observacionesField;
        
        private decimal tipoCambioUSDField;
        
        private bool tipoCambioUSDFieldSpecified;
        
        private decimal totalUSDField;
        
        private bool totalUSDFieldSpecified;
        
        public ComercioExterior() {
            this.versionField = "1.1";
        }
        
        /// <comentarios/>
        public ComercioExteriorEmisor Emisor {
            get {
                return this.emisorField;
            }
            set {
                this.emisorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Propietario")]
        public ComercioExteriorPropietario[] Propietario {
            get {
                return this.propietarioField;
            }
            set {
                this.propietarioField = value;
            }
        }
        
        /// <comentarios/>
        public ComercioExteriorReceptor Receptor {
            get {
                return this.receptorField;
            }
            set {
                this.receptorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Destinatario")]
        public ComercioExteriorDestinatario[] Destinatario {
            get {
                return this.destinatarioField;
            }
            set {
                this.destinatarioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Mercancia", IsNullable=false)]
        public ComercioExteriorMercancia[] Mercancias {
            get {
                return this.mercanciasField;
            }
            set {
                this.mercanciasField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_MotivoTraslado MotivoTraslado {
            get {
                return this.motivoTrasladoField;
            }
            set {
                this.motivoTrasladoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MotivoTrasladoSpecified {
            get {
                return this.motivoTrasladoFieldSpecified;
            }
            set {
                this.motivoTrasladoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_TipoOperacion TipoOperacion {
            get {
                return this.tipoOperacionField;
            }
            set {
                this.tipoOperacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_ClavePedimento ClaveDePedimento {
            get {
                return this.claveDePedimentoField;
            }
            set {
                this.claveDePedimentoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClaveDePedimentoSpecified {
            get {
                return this.claveDePedimentoFieldSpecified;
            }
            set {
                this.claveDePedimentoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int CertificadoOrigen {
            get {
                return this.certificadoOrigenField;
            }
            set {
                this.certificadoOrigenField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CertificadoOrigenSpecified {
            get {
                return this.certificadoOrigenFieldSpecified;
            }
            set {
                this.certificadoOrigenFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumCertificadoOrigen {
            get {
                return this.numCertificadoOrigenField;
            }
            set {
                this.numCertificadoOrigenField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumeroExportadorConfiable {
            get {
                return this.numeroExportadorConfiableField;
            }
            set {
                this.numeroExportadorConfiableField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_INCOTERM Incoterm {
            get {
                return this.incotermField;
            }
            set {
                this.incotermField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncotermSpecified {
            get {
                return this.incotermFieldSpecified;
            }
            set {
                this.incotermFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Subdivision {
            get {
                return this.subdivisionField;
            }
            set {
                this.subdivisionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubdivisionSpecified {
            get {
                return this.subdivisionFieldSpecified;
            }
            set {
                this.subdivisionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TipoCambioUSD {
            get {
                return this.tipoCambioUSDField;
            }
            set {
                this.tipoCambioUSDField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipoCambioUSDSpecified {
            get {
                return this.tipoCambioUSDFieldSpecified;
            }
            set {
                this.tipoCambioUSDFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalUSD {
            get {
                return this.totalUSDField;
            }
            set {
                this.totalUSDField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalUSDSpecified {
            get {
                return this.totalUSDFieldSpecified;
            }
            set {
                this.totalUSDFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/ComercioExterior11")]
    public partial class ComercioExteriorEmisor {
        
        private ComercioExteriorEmisorDomicilio domicilioField;
        
        private string curpField;
        
        /// <comentarios/>
        public ComercioExteriorEmisorDomicilio Domicilio {
            get {
                return this.domicilioField;
            }
            set {
                this.domicilioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Curp {
            get {
                return this.curpField;
            }
            set {
                this.curpField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/ComercioExterior11")]
    public partial class ComercioExteriorEmisorDomicilio {
        
        private string calleField;
        
        private string numeroExteriorField;
        
        private string numeroInteriorField;
        
        private string coloniaField;
        
        private string localidadField;
        
        private string referenciaField;
        
        private string municipioField;
        
        private c_Estado estadoField;
        
        private c_Pais paisField;
        
        private string codigoPostalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumeroExterior {
            get {
                return this.numeroExteriorField;
            }
            set {
                this.numeroExteriorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumeroInterior {
            get {
                return this.numeroInteriorField;
            }
            set {
                this.numeroInteriorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Colonia {
            get {
                return this.coloniaField;
            }
            set {
                this.coloniaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_Estado Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_Pais Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodigoPostal {
            get {
                return this.codigoPostalField;
            }
            set {
                this.codigoPostalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/sitio_internet/cfd/catalogos")]
    public enum c_Estado {
        
        /// <comentarios/>
        AGU,
        
        /// <comentarios/>
        BCN,
        
        /// <comentarios/>
        BCS,
        
        /// <comentarios/>
        CAM,
        
        /// <comentarios/>
        CHP,
        
        /// <comentarios/>
        CHH,
        
        /// <comentarios/>
        COA,
        
        /// <comentarios/>
        COL,
        
        /// <comentarios/>
        DIF,
        
        /// <comentarios/>
        DUR,
        
        /// <comentarios/>
        GUA,
        
        /// <comentarios/>
        GRO,
        
        /// <comentarios/>
        HID,
        
        /// <comentarios/>
        JAL,
        
        /// <comentarios/>
        MEX,
        
        /// <comentarios/>
        MIC,
        
        /// <comentarios/>
        MOR,
        
        /// <comentarios/>
        NAY,
        
        /// <comentarios/>
        NLE,
        
        /// <comentarios/>
        OAX,
        
        /// <comentarios/>
        PUE,
        
        /// <comentarios/>
        QUE,
        
        /// <comentarios/>
        ROO,
        
        /// <comentarios/>
        SLP,
        
        /// <comentarios/>
        SIN,
        
        /// <comentarios/>
        SON,
        
        /// <comentarios/>
        TAB,
        
        /// <comentarios/>
        TAM,
        
        /// <comentarios/>
        TLA,
        
        /// <comentarios/>
        VER,
        
        /// <comentarios/>
        YUC,
        
        /// <comentarios/>
        ZAC,
        
        /// <comentarios/>
        AL,
        
        /// <comentarios/>
        AK,
        
        /// <comentarios/>
        AZ,
        
        /// <comentarios/>
        AR,
        
        /// <comentarios/>
        CA,
        
        /// <comentarios/>
        NC,
        
        /// <comentarios/>
        SC,
        
        /// <comentarios/>
        CO,
        
        /// <comentarios/>
        CT,
        
        /// <comentarios/>
        ND,
        
        /// <comentarios/>
        SD,
        
        /// <comentarios/>
        DE,
        
        /// <comentarios/>
        FL,
        
        /// <comentarios/>
        GA,
        
        /// <comentarios/>
        HI,
        
        /// <comentarios/>
        ID,
        
        /// <comentarios/>
        IL,
        
        /// <comentarios/>
        IN,
        
        /// <comentarios/>
        IA,
        
        /// <comentarios/>
        KS,
        
        /// <comentarios/>
        KY,
        
        /// <comentarios/>
        LA,
        
        /// <comentarios/>
        ME,
        
        /// <comentarios/>
        MD,
        
        /// <comentarios/>
        MA,
        
        /// <comentarios/>
        MI,
        
        /// <comentarios/>
        MN,
        
        /// <comentarios/>
        MS,
        
        /// <comentarios/>
        MO,
        
        /// <comentarios/>
        MT,
        
        /// <comentarios/>
        NE,
        
        /// <comentarios/>
        NV,
        
        /// <comentarios/>
        NJ,
        
        /// <comentarios/>
        NY,
        
        /// <comentarios/>
        NH,
        
        /// <comentarios/>
        NM,
        
        /// <comentarios/>
        OH,
        
        /// <comentarios/>
        OK,
        
        /// <comentarios/>
        OR,
        
        /// <comentarios/>
        PA,
        
        /// <comentarios/>
        RI,
        
        /// <comentarios/>
        TN,
        
        /// <comentarios/>
        TX,
        
        /// <comentarios/>
        UT,
        
        /// <comentarios/>
        VT,
        
        /// <comentarios/>
        VA,
        
        /// <comentarios/>
        WV,
        
        /// <comentarios/>
        WA,
        
        /// <comentarios/>
        WI,
        
        /// <comentarios/>
        WY,
        
        /// <comentarios/>
        ON,
        
        /// <comentarios/>
        QC,
        
        /// <comentarios/>
        NS,
        
        /// <comentarios/>
        NB,
        
        /// <comentarios/>
        MB,
        
        /// <comentarios/>
        BC,
        
        /// <comentarios/>
        PE,
        
        /// <comentarios/>
        SK,
        
        /// <comentarios/>
        AB,
        
        /// <comentarios/>
        NL,
        
        /// <comentarios/>
        NT,
        
        /// <comentarios/>
        YT,
        
        /// <comentarios/>
        UN,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/sitio_internet/cfd/catalogos")]
    public enum c_Pais {
        
        /// <comentarios/>
        AFG,
        
        /// <comentarios/>
        ALA,
        
        /// <comentarios/>
        ALB,
        
        /// <comentarios/>
        DEU,
        
        /// <comentarios/>
        AND,
        
        /// <comentarios/>
        AGO,
        
        /// <comentarios/>
        AIA,
        
        /// <comentarios/>
        ATA,
        
        /// <comentarios/>
        ATG,
        
        /// <comentarios/>
        SAU,
        
        /// <comentarios/>
        DZA,
        
        /// <comentarios/>
        ARG,
        
        /// <comentarios/>
        ARM,
        
        /// <comentarios/>
        ABW,
        
        /// <comentarios/>
        AUS,
        
        /// <comentarios/>
        AUT,
        
        /// <comentarios/>
        AZE,
        
        /// <comentarios/>
        BHS,
        
        /// <comentarios/>
        BGD,
        
        /// <comentarios/>
        BRB,
        
        /// <comentarios/>
        BHR,
        
        /// <comentarios/>
        BEL,
        
        /// <comentarios/>
        BLZ,
        
        /// <comentarios/>
        BEN,
        
        /// <comentarios/>
        BMU,
        
        /// <comentarios/>
        BLR,
        
        /// <comentarios/>
        MMR,
        
        /// <comentarios/>
        BOL,
        
        /// <comentarios/>
        BIH,
        
        /// <comentarios/>
        BWA,
        
        /// <comentarios/>
        BRA,
        
        /// <comentarios/>
        BRN,
        
        /// <comentarios/>
        BGR,
        
        /// <comentarios/>
        BFA,
        
        /// <comentarios/>
        BDI,
        
        /// <comentarios/>
        BTN,
        
        /// <comentarios/>
        CPV,
        
        /// <comentarios/>
        KHM,
        
        /// <comentarios/>
        CMR,
        
        /// <comentarios/>
        CAN,
        
        /// <comentarios/>
        QAT,
        
        /// <comentarios/>
        BES,
        
        /// <comentarios/>
        TCD,
        
        /// <comentarios/>
        CHL,
        
        /// <comentarios/>
        CHN,
        
        /// <comentarios/>
        CYP,
        
        /// <comentarios/>
        COL,
        
        /// <comentarios/>
        COM,
        
        /// <comentarios/>
        PRK,
        
        /// <comentarios/>
        KOR,
        
        /// <comentarios/>
        CIV,
        
        /// <comentarios/>
        CRI,
        
        /// <comentarios/>
        HRV,
        
        /// <comentarios/>
        CUB,
        
        /// <comentarios/>
        CUW,
        
        /// <comentarios/>
        DNK,
        
        /// <comentarios/>
        DMA,
        
        /// <comentarios/>
        ECU,
        
        /// <comentarios/>
        EGY,
        
        /// <comentarios/>
        SLV,
        
        /// <comentarios/>
        ARE,
        
        /// <comentarios/>
        ERI,
        
        /// <comentarios/>
        SVK,
        
        /// <comentarios/>
        SVN,
        
        /// <comentarios/>
        ESP,
        
        /// <comentarios/>
        USA,
        
        /// <comentarios/>
        EST,
        
        /// <comentarios/>
        ETH,
        
        /// <comentarios/>
        PHL,
        
        /// <comentarios/>
        FIN,
        
        /// <comentarios/>
        FJI,
        
        /// <comentarios/>
        FRA,
        
        /// <comentarios/>
        GAB,
        
        /// <comentarios/>
        GMB,
        
        /// <comentarios/>
        GEO,
        
        /// <comentarios/>
        GHA,
        
        /// <comentarios/>
        GIB,
        
        /// <comentarios/>
        GRD,
        
        /// <comentarios/>
        GRC,
        
        /// <comentarios/>
        GRL,
        
        /// <comentarios/>
        GLP,
        
        /// <comentarios/>
        GUM,
        
        /// <comentarios/>
        GTM,
        
        /// <comentarios/>
        GUF,
        
        /// <comentarios/>
        GGY,
        
        /// <comentarios/>
        GIN,
        
        /// <comentarios/>
        GNB,
        
        /// <comentarios/>
        GNQ,
        
        /// <comentarios/>
        GUY,
        
        /// <comentarios/>
        HTI,
        
        /// <comentarios/>
        HND,
        
        /// <comentarios/>
        HKG,
        
        /// <comentarios/>
        HUN,
        
        /// <comentarios/>
        IND,
        
        /// <comentarios/>
        IDN,
        
        /// <comentarios/>
        IRQ,
        
        /// <comentarios/>
        IRN,
        
        /// <comentarios/>
        IRL,
        
        /// <comentarios/>
        BVT,
        
        /// <comentarios/>
        IMN,
        
        /// <comentarios/>
        CXR,
        
        /// <comentarios/>
        NFK,
        
        /// <comentarios/>
        ISL,
        
        /// <comentarios/>
        CYM,
        
        /// <comentarios/>
        CCK,
        
        /// <comentarios/>
        COK,
        
        /// <comentarios/>
        FRO,
        
        /// <comentarios/>
        SGS,
        
        /// <comentarios/>
        HMD,
        
        /// <comentarios/>
        FLK,
        
        /// <comentarios/>
        MNP,
        
        /// <comentarios/>
        MHL,
        
        /// <comentarios/>
        PCN,
        
        /// <comentarios/>
        SLB,
        
        /// <comentarios/>
        TCA,
        
        /// <comentarios/>
        UMI,
        
        /// <comentarios/>
        VGB,
        
        /// <comentarios/>
        VIR,
        
        /// <comentarios/>
        ISR,
        
        /// <comentarios/>
        ITA,
        
        /// <comentarios/>
        JAM,
        
        /// <comentarios/>
        JPN,
        
        /// <comentarios/>
        JEY,
        
        /// <comentarios/>
        JOR,
        
        /// <comentarios/>
        KAZ,
        
        /// <comentarios/>
        KEN,
        
        /// <comentarios/>
        KGZ,
        
        /// <comentarios/>
        KIR,
        
        /// <comentarios/>
        KWT,
        
        /// <comentarios/>
        LAO,
        
        /// <comentarios/>
        LSO,
        
        /// <comentarios/>
        LVA,
        
        /// <comentarios/>
        LBN,
        
        /// <comentarios/>
        LBR,
        
        /// <comentarios/>
        LBY,
        
        /// <comentarios/>
        LIE,
        
        /// <comentarios/>
        LTU,
        
        /// <comentarios/>
        LUX,
        
        /// <comentarios/>
        MAC,
        
        /// <comentarios/>
        MDG,
        
        /// <comentarios/>
        MYS,
        
        /// <comentarios/>
        MWI,
        
        /// <comentarios/>
        MDV,
        
        /// <comentarios/>
        MLI,
        
        /// <comentarios/>
        MLT,
        
        /// <comentarios/>
        MAR,
        
        /// <comentarios/>
        MTQ,
        
        /// <comentarios/>
        MUS,
        
        /// <comentarios/>
        MRT,
        
        /// <comentarios/>
        MYT,
        
        /// <comentarios/>
        MEX,
        
        /// <comentarios/>
        FSM,
        
        /// <comentarios/>
        MDA,
        
        /// <comentarios/>
        MCO,
        
        /// <comentarios/>
        MNG,
        
        /// <comentarios/>
        MNE,
        
        /// <comentarios/>
        MSR,
        
        /// <comentarios/>
        MOZ,
        
        /// <comentarios/>
        NAM,
        
        /// <comentarios/>
        NRU,
        
        /// <comentarios/>
        NPL,
        
        /// <comentarios/>
        NIC,
        
        /// <comentarios/>
        NER,
        
        /// <comentarios/>
        NGA,
        
        /// <comentarios/>
        NIU,
        
        /// <comentarios/>
        NOR,
        
        /// <comentarios/>
        NCL,
        
        /// <comentarios/>
        NZL,
        
        /// <comentarios/>
        OMN,
        
        /// <comentarios/>
        NLD,
        
        /// <comentarios/>
        PAK,
        
        /// <comentarios/>
        PLW,
        
        /// <comentarios/>
        PSE,
        
        /// <comentarios/>
        PAN,
        
        /// <comentarios/>
        PNG,
        
        /// <comentarios/>
        PRY,
        
        /// <comentarios/>
        PER,
        
        /// <comentarios/>
        PYF,
        
        /// <comentarios/>
        POL,
        
        /// <comentarios/>
        PRT,
        
        /// <comentarios/>
        PRI,
        
        /// <comentarios/>
        GBR,
        
        /// <comentarios/>
        CAF,
        
        /// <comentarios/>
        CZE,
        
        /// <comentarios/>
        MKD,
        
        /// <comentarios/>
        COG,
        
        /// <comentarios/>
        COD,
        
        /// <comentarios/>
        DOM,
        
        /// <comentarios/>
        REU,
        
        /// <comentarios/>
        RWA,
        
        /// <comentarios/>
        ROU,
        
        /// <comentarios/>
        RUS,
        
        /// <comentarios/>
        ESH,
        
        /// <comentarios/>
        WSM,
        
        /// <comentarios/>
        ASM,
        
        /// <comentarios/>
        BLM,
        
        /// <comentarios/>
        KNA,
        
        /// <comentarios/>
        SMR,
        
        /// <comentarios/>
        MAF,
        
        /// <comentarios/>
        SPM,
        
        /// <comentarios/>
        VCT,
        
        /// <comentarios/>
        SHN,
        
        /// <comentarios/>
        LCA,
        
        /// <comentarios/>
        STP,
        
        /// <comentarios/>
        SEN,
        
        /// <comentarios/>
        SRB,
        
        /// <comentarios/>
        SYC,
        
        /// <comentarios/>
        SLE,
        
        /// <comentarios/>
        SGP,
        
        /// <comentarios/>
        SXM,
        
        /// <comentarios/>
        SYR,
        
        /// <comentarios/>
        SOM,
        
        /// <comentarios/>
        LKA,
        
        /// <comentarios/>
        SWZ,
        
        /// <comentarios/>
        ZAF,
        
        /// <comentarios/>
        SDN,
        
        /// <comentarios/>
        SSD,
        
        /// <comentarios/>
        SWE,
        
        /// <comentarios/>
        CHE,
        
        /// <comentarios/>
        SUR,
        
        /// <comentarios/>
        SJM,
        
        /// <comentarios/>
        THA,
        
        /// <comentarios/>
        TWN,
        
        /// <comentarios/>
        TZA,
        
        /// <comentarios/>
        TJK,
        
        /// <comentarios/>
        IOT,
        
        /// <comentarios/>
        ATF,
        
        /// <comentarios/>
        TLS,
        
        /// <comentarios/>
        TGO,
        
        /// <comentarios/>
        TKL,
        
        /// <comentarios/>
        TON,
        
        /// <comentarios/>
        TTO,
        
        /// <comentarios/>
        TUN,
        
        /// <comentarios/>
        TKM,
        
        /// <comentarios/>
        TUR,
        
        /// <comentarios/>
        TUV,
        
        /// <comentarios/>
        UKR,
        
        /// <comentarios/>
        UGA,
        
        /// <comentarios/>
        URY,
        
        /// <comentarios/>
        UZB,
        
        /// <comentarios/>
        VUT,
        
        /// <comentarios/>
        VAT,
        
        /// <comentarios/>
        VEN,
        
        /// <comentarios/>
        VNM,
        
        /// <comentarios/>
        WLF,
        
        /// <comentarios/>
        YEM,
        
        /// <comentarios/>
        DJI,
        
        /// <comentarios/>
        ZMB,
        
        /// <comentarios/>
        ZWE,
        
        /// <comentarios/>
        ZZZ,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/ComercioExterior11")]
    public partial class ComercioExteriorPropietario {
        
        private string numRegIdTribField;
        
        private c_Pais residenciaFiscalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumRegIdTrib {
            get {
                return this.numRegIdTribField;
            }
            set {
                this.numRegIdTribField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_Pais ResidenciaFiscal {
            get {
                return this.residenciaFiscalField;
            }
            set {
                this.residenciaFiscalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/ComercioExterior11")]
    public partial class ComercioExteriorReceptor {
        
        private ComercioExteriorReceptorDomicilio domicilioField;
        
        private string numRegIdTribField;
        
        /// <comentarios/>
        public ComercioExteriorReceptorDomicilio Domicilio {
            get {
                return this.domicilioField;
            }
            set {
                this.domicilioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumRegIdTrib {
            get {
                return this.numRegIdTribField;
            }
            set {
                this.numRegIdTribField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/ComercioExterior11")]
    public partial class ComercioExteriorReceptorDomicilio {
        
        private string calleField;
        
        private string numeroExteriorField;
        
        private string numeroInteriorField;
        
        private string coloniaField;
        
        private string localidadField;
        
        private string referenciaField;
        
        private string municipioField;
        
        private string estadoField;
        
        private c_Pais paisField;
        
        private string codigoPostalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumeroExterior {
            get {
                return this.numeroExteriorField;
            }
            set {
                this.numeroExteriorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumeroInterior {
            get {
                return this.numeroInteriorField;
            }
            set {
                this.numeroInteriorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Colonia {
            get {
                return this.coloniaField;
            }
            set {
                this.coloniaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_Pais Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodigoPostal {
            get {
                return this.codigoPostalField;
            }
            set {
                this.codigoPostalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/ComercioExterior11")]
    public partial class ComercioExteriorDestinatario {
        
        private ComercioExteriorDestinatarioDomicilio[] domicilioField;
        
        private string numRegIdTribField;
        
        private string nombreField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Domicilio")]
        public ComercioExteriorDestinatarioDomicilio[] Domicilio {
            get {
                return this.domicilioField;
            }
            set {
                this.domicilioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumRegIdTrib {
            get {
                return this.numRegIdTribField;
            }
            set {
                this.numRegIdTribField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/ComercioExterior11")]
    public partial class ComercioExteriorDestinatarioDomicilio {
        
        private string calleField;
        
        private string numeroExteriorField;
        
        private string numeroInteriorField;
        
        private string coloniaField;
        
        private string localidadField;
        
        private string referenciaField;
        
        private string municipioField;
        
        private string estadoField;
        
        private c_Pais paisField;
        
        private string codigoPostalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumeroExterior {
            get {
                return this.numeroExteriorField;
            }
            set {
                this.numeroExteriorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumeroInterior {
            get {
                return this.numeroInteriorField;
            }
            set {
                this.numeroInteriorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Colonia {
            get {
                return this.coloniaField;
            }
            set {
                this.coloniaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_Pais Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodigoPostal {
            get {
                return this.codigoPostalField;
            }
            set {
                this.codigoPostalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/ComercioExterior11")]
    public partial class ComercioExteriorMercancia {
        
        private ComercioExteriorMercanciaDescripcionesEspecificas[] descripcionesEspecificasField;
        
        private string noIdentificacionField;
        
        private string fraccionArancelariaField;
        
        private decimal cantidadAduanaField;
        
        private bool cantidadAduanaFieldSpecified;
        
        private c_UnidadAduana unidadAduanaField;
        
        private bool unidadAduanaFieldSpecified;
        
        private decimal valorUnitarioAduanaField;
        
        private bool valorUnitarioAduanaFieldSpecified;
        
        private decimal valorDolaresField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("DescripcionesEspecificas")]
        public ComercioExteriorMercanciaDescripcionesEspecificas[] DescripcionesEspecificas {
            get {
                return this.descripcionesEspecificasField;
            }
            set {
                this.descripcionesEspecificasField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NoIdentificacion {
            get {
                return this.noIdentificacionField;
            }
            set {
                this.noIdentificacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FraccionArancelaria {
            get {
                return this.fraccionArancelariaField;
            }
            set {
                this.fraccionArancelariaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal CantidadAduana {
            get {
                return this.cantidadAduanaField;
            }
            set {
                this.cantidadAduanaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CantidadAduanaSpecified {
            get {
                return this.cantidadAduanaFieldSpecified;
            }
            set {
                this.cantidadAduanaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_UnidadAduana UnidadAduana {
            get {
                return this.unidadAduanaField;
            }
            set {
                this.unidadAduanaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnidadAduanaSpecified {
            get {
                return this.unidadAduanaFieldSpecified;
            }
            set {
                this.unidadAduanaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ValorUnitarioAduana {
            get {
                return this.valorUnitarioAduanaField;
            }
            set {
                this.valorUnitarioAduanaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorUnitarioAduanaSpecified {
            get {
                return this.valorUnitarioAduanaFieldSpecified;
            }
            set {
                this.valorUnitarioAduanaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ValorDolares {
            get {
                return this.valorDolaresField;
            }
            set {
                this.valorDolaresField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/ComercioExterior11")]
    public partial class ComercioExteriorMercanciaDescripcionesEspecificas {
        
        private string marcaField;
        
        private string modeloField;
        
        private string subModeloField;
        
        private string numeroSerieField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubModelo {
            get {
                return this.subModeloField;
            }
            set {
                this.subModeloField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumeroSerie {
            get {
                return this.numeroSerieField;
            }
            set {
                this.numeroSerieField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/ComExt")]
    public enum c_UnidadAduana {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("19")]
        Item19,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("21")]
        Item21,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/ComExt")]
    public enum c_MotivoTraslado {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/ComExt")]
    public enum c_TipoOperacion {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/ComExt")]
    public enum c_ClavePedimento {
        
        /// <comentarios/>
        A1,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/ComExt")]
    public enum c_INCOTERM {
        
        /// <comentarios/>
        CFR,
        
        /// <comentarios/>
        CIF,
        
        /// <comentarios/>
        CPT,
        
        /// <comentarios/>
        CIP,
        
        /// <comentarios/>
        DAF,
        
        /// <comentarios/>
        DAP,
        
        /// <comentarios/>
        DAT,
        
        /// <comentarios/>
        DES,
        
        /// <comentarios/>
        DEQ,
        
        /// <comentarios/>
        DDU,
        
        /// <comentarios/>
        DDP,
        
        /// <comentarios/>
        EXW,
        
        /// <comentarios/>
        FCA,
        
        /// <comentarios/>
        FAS,
        
        /// <comentarios/>
        FOB,
    }
}
